version: 2
jobs:
  build:
    Machine:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
             sudo pip install pipenv
             pipenv install
            
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - "venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Running tests
          command: |
             pipenv run python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
